---
editor_options: 
  chunk_output_type: console
---

```{r load_libs}
source("libs.R");source("ggplot.pub.r")
library(readr);library(viridis)
```

```{r load_cleaned_subset_data}
#'load knots01_data
load("knots02_data.rdata")

#'how many datapoints overall? a lot
sum(unlist(map(k2.data, function(x)dim(x)[1])))
```

```{r temporal_range}
#'subset 10 knots
k2.subset = k2.data
#'remove the main data and gc
rm(k2.data);gc()

#'assign tag id
for (i in 1:length(k2.subset)){
  k2.subset[[i]]$id = names(k2.subset)[i]
}

#'bind rows
k2 = k2.subset %>% bind_rows()

rm(k2.subset)
```

```{r summarise_data}
#'summary for id and time
#summary(k2)
count(k2, id)

#'get the tracking day
k2 = k2 %>% mutate(day = round_any(as.numeric(julian(ts, origin = min(k2$ts))), 0.1))

```

```{r plot_fix_density, eval=FALSE, include=FALSE}
#'plot a density curve
ggplot(k2)+
  stat_density(aes(x = day, group = id, col = id), geom = "line")+
  theme_pub()

#'plot the number of positions per day per bird
plot2 = k2 %>% group_by(id, day) %>% summarise(n = length(ts)) %>% 
ggplot()+
  geom_tile(aes(x = id, y = day, fill = n))+
  scale_fill_gradientn(colours  = (viridis(20)))+
  coord_flip()+
  theme_pub()+theme(legend.position = "top", axis.line.y = element_blank(), legend.text = element_text(angle= 10, colour = "white"), legend.background = element_rect(fill = 1), plot.background = element_rect(fill=1), axis.text = element_text(colour = "white"), legend.title = element_text(colour = "white"))
```


```{r subset_in_time}
#'get first five days of obs
k2.5daysubset = k2 %>% filter(day <= 5)

#'save as rdata
save(k2.5daysubset, file = "knots02_5daysubset.rdata")
```

