
```{r make neutral landscape}
library(rayshader);library(NLMR)

#'make localtiff from circular and gaussian gradient
localtif = (1-nlm_distancegradient(100,100, origin = c(50,50,50,50)))*100 + (nlm_gaussianfield(100, 100, autocorr_range = 20)*10)

#'make elevation matrix
elmat = matrix(raster::extract(localtif,raster::extent(localtif),buffer=1e3),nrow=ncol(localtif),ncol=nrow(localtif))
```


```{r output png for shading}
#### rayshader examples #####
png("elevation_shading.png", width=ncol(localtif), height=nrow(localtif), units = "px", pointsize = 1)

par(mar = c(0,0,0,0), xaxs = "i", yaxs = "i") #Parameters to create a borderless image

library(cptcity)
pal = cpt(pal = "esri_hypsometry_na_pnw_1113", n = 120, colorRampPalette = T)

raster::image(
  localtif,
  col = pal(120)[1:100],
  maxpixels = raster::ncell(localtif),
  axes = FALSE
)

dev.off()
```

```{r load image}
terrain_image <- png::readPNG("elevation_shading.png")

#'write two images, 20% to 80% to file
for(i in c(2,5,8)){
  terrain_image %>% 
  add_shadow(ray_shade(elmat,zscale=5,maxsearch = 300),0.7) %>%
 plot_3d(elmat,zscale=10,fov=0,theta=30,zoom=0.75,phi=30, windowsize = c(600,500), water = T, waterdepth = i, wateralpha = 0.5)

  rgl.snapshot(filename = paste("tidal_landscape", i, ".png", sep = "_"), fmt = "png")
  rgl.close()
}
```

```{r plot for essay}
#'combine with imagemagick
library(magick)

images = list.files(pattern = "tidal_landscape", full.names = T) %>% map(image_read)

landscape = image_append(c(images[[1]], images[[2]], images[[3]]))
image_write(landscape, path = "tidal_landscape_composite.png", density = 300)
```

# plot tidal cycle 2d

```{r plot graphic of tidal system}
#'get water level over 10 tidal cycles
maxWaterHeight = 0.8; tidalInterval = 780

waterlevel = data_frame(waterlevel = maxWaterHeight - ((maxWaterHeight/2)*cos((2*pi/tidalInterval)*(1:(tidalInterval*10))) + maxWaterHeight/2), time = c(1:7800))

library(extrafont)
#'print water level
ggplot(waterlevel)+
  geom_path(aes(x = time, y = waterlevel))+
  geom_vline(xintercept = (1:10)*780, col = 2, lty = 2, lwd = 0.2)+
  geom_hline(yintercept = 0.8, col = "dodgerblue", lty = 2)+
  theme_pub()+
  theme(text = element_text(family = "Fira Sans"))+
  labs(x = "Time since start (mins)", y = "Relative water height")+
  xlim(0, 780*3)+ylim(0,1)

ggsave(filename = "tidal_waterlevel.png", device = png(), width = 180/25.4, height = 50/25.4); dev.off()
```

