---
editor_options: 
  chunk_output_type: console
---

```{r load_libs}
source("libs.R")
library(readr);library(viridis)
```

```{r load_all_birds}
#'load all birds
load("birds.all.rdata")

#'subset for knots 02
knots2 = birds.all %>% filter(batch == "knots02")
#'subset for 5 days since tracking
knots2 = knots2 %>% mutate(day = round(as.numeric(julian(ts, origin = min(ts))))) %>% filter(day <= 2)

#'get knots with at least 0.006% of points recorded
filtered_data_ids = knots2 %>% dlply("id") %>% map(function(x) nrow(x)/abs(x$TIME[1] - x$TIME[nrow(x)])) %>% bind_rows() %>% t() %>% data.frame() %>% rename(prop = ".") %>%  bind_cols(count(knots2, id)) %>% filter(prop> 6e-5) %>% .$id

#'remove all birds
rm(birds.all)
#'filter the data for only these ids
knots2 = knots2 %>% filter(id %in% filtered_data_ids)
```

```{r get_extent_centroid}
#'get the spatial extent and the centroid, make a circular polygon of some reasonable radius
library(sf)
k2.sf = st_as_sf(knots2, coords = c("X","Y"))
k2.centroid = st_centroid(st_as_sfc(st_bbox(k2.sf)))
#'4km buffer
k2.buffer = st_buffer(k2.centroid, dist = 4e3)

#'write buffer to file
library(rgdal)
st_write(k2.buffer, dsn = ".", layer = "griend_4km_buffer", driver = "ESRI Shapefile", delete_layer = T)
```

```{r check_for_points_inside}
#'check if the points are within 4km of the centroid, which should be the centre of griend
k2.within = st_intersects(k2.buffer, k2.sf)

#'assign index to k2.sf
k2.sf$index = seq(1, nrow(k2.sf), 1)

#'inner join with k2.within
k2.pts.within = knots2 %>% mutate(index = seq(1, nrow(knots2))) %>% left_join(data_frame(pts = k2.within[[1]], within = T), by = c("index" = "pts")) %>% mutate(within = ifelse(is.na(within), F, T))
```

```{r classify_segments}
#'convert to list
k2.pts.within = k2.pts.within %>% dlply("id")

#'run inside a list
for(i in 1:length(k2.pts.within)){
  x = k2.pts.within[[i]]
  a = data.frame(unclass(rle(x$within)))
  x = x %>% filter(within == T) %>% mutate(segment = rep(c(1:nrow(a[a$values==T,])), c(a[a$values ==T,]$lengths)))
  k2.pts.within[[i]] = x
}

#'save data
#save(k2.pts.within, file = "k2.segments.rdata")
```


```{r load_pskf_functions}
#'source from file
source("~/git/huji_atlas_pskf_code/PSKF/PSKFForATLAS.R")
```

```{r run_pskf}
#'get only data with a greater than 0.006% recording rate
pskf_data_ids = k2.pts.within %>% rbind_list() %>% group_by(id, segment) %>% summarise(prop = length(TIME)/(max(TIME) - min(TIME))) %>%  filter(prop> 0.005) %>% mutate(id.seg = paste(id,segment, sep =".")) %>% .$id.seg

pskf_data = k2.pts.within %>% rbind_list() %>% mutate(id.seg = paste(id, segment, sep = ".")) %>% filter(id.seg %in% pskf_data_ids) %>% dlply(c("id.seg")) %>% 
  map(function(x) x %>% arrange(TIME) %>% select(X,Y,COVXY,VARX,VARY,TIME))

#"run pskf and write to csv"
for(i in 67:length(pskf_data)){
  x = PSKFForATLAS(pskf_data[[i]])
  write_csv(x, path = paste("knots_data/knots_pskf/",names(pskf_data)[i],"pskf.csv", sep=""))
  rm(x)
  gc()
}
```

```{r load_pskf_data}
#'load from csv
pskf_files = list.files("knots_data/knots_pskf/", pattern = "pskf.csv", full.names = T)

#'run map
pskf_files = pskf_files %>% map(read_csv)
#'assign names
names(pskf_files) = pskf_data_ids
for(i in 1:length(pskf_files)){
  pskf_files[[i]]$id = filtered_data_ids[i]
}
```

