---
editor_options:
  chunk_output_type: console
---

```{r load_libs}
source("libs.R")
library(readr);library(viridis)
source("libs.spatial.r")

```

```{r load_data}
#'loadpskf data
#load("knots_data/pskf_data.rdata")
```

```{r make_lines}
#'use same template as k2-data
k1.lines = data.tide.move %>%
  filter(ht.time %between% c(3.5*3600,9.5*3600), distance < 2e3, fpt > 10/60) %>% 
  dlply(c("id","ht")) %>%
  #map(function(x) x %>% filter(Std<100)) %>%
  map(function(x) Line(cbind(x$x, x$y)))

k1.lines = k1.lines %>%
  map(function(x) Lines(x, ID = "a"))

for(i in 1:length(k1.lines)) {
  k1.lines[[i]]@ID = names(k1.lines)[i]
}
```

```{r make_spatial_lines}
names = names(k1.lines)

#'use the UTM 31N CRS
k1.lines = SpatialLines(k1.lines, proj4string = CRS("+proj=utm +zone=31 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
+towgs84=0,0,0"))

library(stringi)

data = data_frame(index = 1:length(k1.lines),names)# %>% left_join(pskf_data_ids[[1]], by = c("names2" = "id.seg"))

rownames(data) = names

k1.lines = SpatialLinesDataFrame(k1.lines, data = data)

#'export
library(rgdal)
writeOGR(k1.lines, dsn = "knots_data/knots_spatials/", layer = "k1_low_tide", driver = "ESRI Shapefile", overwrite_layer = T)
```
