---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
source("libs.R");library(sp)
load("knots_data/kntoscode023_tidematched_data.rdata")
library(stringi)
#'get ht data, get the FLOORed hour, not the rounded
data <- unclass(data.tide) %>% 
  bind_rows() %>% 
  #anti_join(unclass(data.lt) %>% bind_rows()) %>% 
  mutate(hour = stri_pad(floor(ht.time/3600), width = 2, pad = "0"),
         ht = stri_pad(ht, width = 2, pad = "0"))

#'assign a tidal interval
data <- data %>% 
 # map(function(x){
 #   mutate(x, tide = ifelse(is.na(tide),"other",tide),
 #          lt = cumsum(tide == "L")+1) %>% 
 #     filter(tide != "L")
 #}) %>% unclass() %>% bind_rows() %>% 
  dlply(c("ht","hour"))

#'remove tides with < 5 birds
data <- data[unlist(lapply(data, function(x) length(unique(x$id[!is.na(x$id)])))) >= 5]
```

```{r get_proximities}
library(sp)
#'this method is simpler than in knotscode019.
proximity <- data_frame()

for(z in 1:length(data)){
#'split again by id
focals <- dlply(data[[z]], "id")  
#'implement method from knotscode019
for(i in 1:length(focals)){
  #'get focals
  #'get the nonfocal birds
  nonfocals <- focals[!names(focals) %in% names(focals)[i]]
  
  #'loop over nonfocals
  for(j in 1:length(nonfocals)){
    distances <- spDists(as.matrix(focals[[i]][,c("X","Y")]), as.matrix(nonfocals[[j]][,c("X","Y")]), diagonal = T)
    #'get only distances where both focal and nonfocal positions are known
    #'set all distances greater than 9e6 = 0, and all rows where focal pos and all cols where nonfocal pos are > 9e6
    distances[focals[[i]]$X > 9e6 | nonfocals[[j]]$Y > 9e6] <- NA
    #distances <- diag(distances)
    interactions <- data_frame(distances = sum(distances <= 250, na.rm = T)) %>%
      #count(class) %>% 
      mutate(focal = unique(focals[[i]]$id), 
             nonfocal = unique(nonfocals[[j]]$id), 
             ht = unique(focals[[i]]$ht),
             hour = unique(focals[[i]]$hour),
             pos_focal = sum(focals[[i]]$X < 9e9), 
             pos_nonfocal = sum(nonfocals[[j]]$X < 9e9))
    proximity <- rbind(proximity, interactions)
    }
  }
}
```

```{r get_unique_pairs}
#'find unique pairs
pairs <- expand(proximity, focal, nonfocal) %>% 
  filter(focal < nonfocal) %>% mutate(pair = 1:nrow(.))

#'remove non-unique pairs
proximity_compare <- proximity %>% 
  left_join(pairs) %>% filter(!is.na(pair))
```

```{r remove_few_pairs}
#'remove pairs with less than 30 positions overall and hour-tide-wise data with under 5 focal bird positions

proximity_compare <- proximity_compare %>% 
  group_by(pair,hour) %>% 
  mutate(n = length(distances))# %>% 
  #filter(n >= 30, pos_focal > 5)

#'get hour-tide-wise coherence
proximity_compare <- mutate(ungroup(proximity_compare),
                            c_emp = distances/pos_focal,
                            hour = as.numeric(hour))
```

# KS test

```{r run hourwise KS test}
#'prep proximity for testing anti-join
proximity_aj <- proximity_compare

#'split prox_compare by id and hour
proximity_compare <- proximity_compare %>%
  filter(n >= 10) %>% 
  dlply(c("pair","hour"))

#proximity_compare <- proximity_compare[unlist(lapply(proximity_compare, nrow)) >= 10]

for(i in 1:length(proximity_compare)){

x <- proximity_compare[[i]]
y <- proximity_aj %>% anti_join(x) %>% filter(hour == unique(x$hour)) %>% .$c_emp

#'run the KS test
ks.res <- bind_cols(unclass(ks.test(x = x$c_emp, y = y)))

#'get emp mean and sim mean
x <- summarise(x, c_emp = mean(c_emp, na.rm = T),
                 c_sim = mean(y, na.rm = T),
               hour = unique(hour),
               pair = unique(pair))
proximity_compare[[i]] <- x %>% bind_cols(ks.res)
}

#'bind the list rows
pairs_test <- bind_rows(unclass(proximity_compare)) %>%
  #'bind the test data to the pairs data
  left_join(pairs) %>%
  dplyr::select(statistic, hour, p.value, pair, focal, nonfocal, c_emp, c_sim)
```


```{r coherence_over_time}
cij_5_top <- proximity_aj %>% 
    #filter(c_emp>0) %>% 
                #group_by(focal,hour) %>% 
                #summarise(c_emp = mean(head(sort(c_emp, decreasing = T), n = 10))) %>%
 # ungroup() %>% 
               group_by(hour) %>% 
               summarise(c_empm = mean(c_emp, na.rm = T),
                         sd = sd(c_emp, na.rm = T),
                         n = sum(!is.na(c_emp))) %>% 
               mutate(ci = qnorm(0.975)*sd/sqrt(n))

#plot coherence over tidal time
cairo_ps(filename = "figure_coherence_hour_handout.eps", width = 100/25.4, height = 100/25.4)

ggplot()+
  
  
  geom_segment(aes(x = 6.5, xend = 6.5, y=0, yend = .3), colour =1, lty = 2)+
  geom_segment(aes(x = c(-0.2, 3.8, 9.8), xend = c(3.3,9.2, 12.2), y=.32, yend = .32), colour =1, lty = 1)+
  #geom_rect(aes(xmin = 3.5, xmax = 9.5, ymin = 0, ymax = 1), fill = cola1, alpha = 0.3)+
 # geom_flat_violin(data = proximity_aj,
       #       aes(x = (hour), y = c_emp, group = hour), colour= "transparent",fill = "orange", width = 3)+
  #geom_boxplot(data = proximity_aj,aes(x = as.factor(hour), y = c_emp), shape = 1, size = 0.1, colour = "grey80", width = 0.2)+
  #geom_line(data = cij_5_top,
              #aes(x = (hour), y = (c_empm+ci),
              #     colour = "10 highest \n co-occurrences per id \n ± 95% CI"),
             # shape = 1, lty=1, col ="grey")+
  geom_ribbon(data = cij_5_top,
              aes(x = (hour), ymin = (c_empm-ci),ymax = (c_empm+ci)),
              shape = 1, lty=1, fill ="grey90", colour = "transparent")+
  geom_line(data = cij_5_top,
              aes(x = (hour), y = c_empm),
            shape = 16)+
 # geom_point(data = cij_5_top,aes(x = (hour), y = c_empm*3, colour = "10 highest \n co-occurrences per id \n ± 95% CI"),shape = 16)+
  #scale_y_continuous(sec.axis = dup_axis(~./3, name = "Mean pair-wise co-occurrence ± 95% CI"))+
  
  geom_text(aes(x = c(0,6,12), y = .33, label = c("Receding tide","Low tide","Advancing tide")), hjust = c("inward","inward","right"),size = 4, family = "serif")+
  #scale_colour_manual(values = 1)+
  #scale_fill_viridis(option = "plasma", guide = F)+
  theme_tufte(base_family = "TeX Gyre Bonum",base_size = 10)+
  theme(legend.position = "none")+
  #theme(panel.grid.major = element_line(size = 0.2), panel.ontop = T)+
  coord_cartesian(ylim = c(-.05,0.35), xlim = c(0,12), expand = F)+
 # scale_x_continuous(breaks = c(0:12))+
  #xlim(-0.5,11.5)+
  labs(list(x = "Hours after high tide", y = "Mean pair-wise co-occurrence", colour = NULL))

dev.off()
```


```{r what_explains_coherence}
#'get coherence n-1, remove pairs with less than 3 tides of presence
cij <- group_by(proximity, pair, ht, hour) %>% 
  mutate(nn = length(c_emp)) %>% 
  filter(nn >= 2)# %>% 
  mutate(cij, cn1 = c(NA, c_emp[2:length(c_emp)]))
#'only consider rows with 10+ positions focal and nonfocal
#cij <- filter(cij, pos_focal >= 10, pos_nonfocal >= 10)
```

```{r pairs_per_time_plot}
pairs_per_tide <- ungroup(proximity_compare) %>% distinct(ht,pair) %>% count(ht)

pairs_per_hour <- ungroup(proximity_compare) %>% distinct(ht,hour,pair) %>% count(ht,hour) %>% mutate(time = as.numeric(ht)+(hour/max(hour)))

cairo_ps(filename = "figure_pairs_per_time.eps", width = 200/25.4, height = 200/25.4)

ggplot()+
  #geom_point(data = pairs_per_hour, aes(x = time, y = n, col = "Pairs per hour"), size = 1, shape = 1)+
  geom_path(data = pairs_per_hour, aes(x = time, y = n, col = "Pairs per hour"))+
  #geom_point(data = pairs_per_hour, aes(x = time, y = n, col = "Pairs per hour"),shape = 21, fill = "white", size = 2)+
  geom_path(data = pairs_per_tide, aes(x = as.numeric(ht), y = n, col = "Pairs per tidal interval"), size = 1)+
  #scale_y_continuous(sec.axis = sec_axis(~.*(1/561)*100, name = "% potential pairs"))+
  xlim(3,NA)+
  theme_poster()+
  labs(list(colour = NULL, x = "tidal interval", y = "# pairs"))+
  scale_color_manual(values = brewer.pal(9, "Blues")[c(5,9)])

dev.off()
```

```{r}
#'model for coherence consistency
library(glmmTMB)
cij$pair = as.factor(cij$pair)
#'run zero inflated glmm for coherence consistency
mod.coherence.consistency = glmmTMB(coherence_emp ~ cn1 + sqrt(hour) + (1|pair) + (1|ht), data = cij, family = binomial, ziformula = ~1)
```

# Coherence and distance mismatch

```{r cooc and distance mismatch}
#'get distances travelled during foraging in each tide by each bird
forage.distances <- ungroup(bind_rows(unclass(data))) %>% filter(as.numeric(hour) %in% c(4:9)) %>% group_by(id, ht) %>% summarise(dist_forage = sum(distance, na.rm = T))

#'get distance mismatch
dist.mismatch <- (proximity_aj) %>% 
  filter(pos_focal > 10, pos_nonfocal > 10) %>% 
  left_join(forage.distances, by = c("focal" = "id","ht")) %>% 
  rename(dist_forage_focal = dist_forage) %>% 
  left_join(forage.distances, by = c("nonfocal" = "id","ht")) %>% 
  rename(dist_forage_nf = dist_forage) %>% 
  select(focal, nonfocal, pair, ht, dist_forage_focal, dist_forage_nf, pos_focal,pos_nonfocal) %>% 
  mutate(mismatch = abs(dist_forage_nf - dist_forage_focal)) %>% 
  filter(dist_forage_focal > 0, dist_forage_nf > 0)

#'advancing - receding coherence
cij.state <- filter(proximity_aj, !hour %in% c(4:9)) %>% 
  mutate(state = ifelse(hour < 4, "receding","advancing")) %>% 
  group_by(pair, state, ht) %>% 
  summarise(c = mean(c_emp, na.rm = T)) %>% 
  spread(state, c)

#'handle factors
cij.state <- cij.state %>% filter(!is.na(advancing), !is.na(receding)) %>% 
  inner_join(ungroup(dist.mismatch), by = c("pair","ht")) %>% 
    distinct(pair, ht, mismatch, advancing, receding) %>% 
  ungroup() %>% 
  mutate(pair = as.factor(pair), ht = as.factor(ht))
```

```{r}
library(glmmTMB)
mod.c.cons.state <- glmmTMB(advancing ~ receding + sqrt(mismatch) + (1|pair)+(1|ht), data = cij.state, family = binomial, ziformula = ~1)

mccs = visreg::visreg(mod.c.cons.state, xvar = "mismatch", scale = "response", plot = F)$fit
```

```{r}
#'plot cij ~ distm
cairo_ps(filename = "figure_coherence_friends_handout.eps", width = 100/25.4, height = 100/25.4)


ggplot()+
  #geom_point(data = cij.state, aes(x = mismatch, y = abs(receding - advancing)), col = "grey80", shape = 1, size = 0.1)+
  geom_ribbon(data = mccs, aes(x = mismatch, ymin = visregLwr, ymax = visregUpr), fill = "grey50", alpha = 0.3)+
  geom_line(data = mccs, aes(x = mismatch, y = visregFit), col = 1)+
  #geom_text(aes(x = 3.9e3,y=100, label = "GLMM \n z-statistic = -3.85 \n P-value < 0.001"), size = 8, vjust = "inward", hjust = "outward")+
  theme_tufte(base_family = "Linux Libertine O")+
  xlim(0,5e3)+
  #theme(axis.text = element_text(size = 16), axis.title = element_text(size = 20))+
  labs(list(x = "Pairwise distance mismatch during foraging (m)", y = "Pairwise co-occurrence after foraging"))

dev.off()
```