---
chunk_output_type: console
---
```{r}
#'source libs
source("libs.R")
library(readr);library(stringi)
```

```{r}
#'read in segmented data
load("knots_data/knots01_segmented.rdata")
```

```{r}
#'identify segments where the median position of the next segment is less than 250m away, and assign a new segment number.
#'there has to be a temporal component to this. if a segment's median is > 5mins from the prev segment median, AND if the proximity criterion is satisfied, count a new segments

for(i in 1:length(data.segpaths)){
  a = data.segpaths[[i]]
  a = a %>% 
    group_by(state) %>% 
    summarise(x.med = median(x), y.med = median(y), time.med = median(time)) %>% 
    mutate(time.diff = c(0, diff(time.med)))
  
  b = as.matrix(dist(as.matrix(a[,c("x.med","y.med")])))
  b = b[row(b) - col(b) == 1]
  c = c(0, b)
  a$dist = c
  a$new.seg = cumsum(c > 250 & a$time.diff/60 > 5)+1
  data.segpaths[[i]] = data.segpaths[[i]] %>% 
    left_join(a, by = "state")
}

#'see example: 151.003 is reclassified into 6 segments instead of 8
x = data.segpaths[[1]]; count(x, new.seg)

library(ggplot2)
#'plot example
x %>% select(x,y,state,new.seg) %>% 
  melt(id.vars = c("x","y")) %>% 
  ggplot()+
  geom_point(aes(x = x, y = y, col = as.factor(value)), size = 4)+
  scale_color_brewer(palette = "Set1")+
  facet_wrap(~variable, ncol = 1)
```

```{r}
#'summarise data for distance matrix between the segments
data.segpaths = data.segpaths %>% 
  bind_rows() %>% 
  group_by(id.ht, new.seg) %>% 
  summarise(x.med = median(x),
            y.med = median(y),
            seg.dur = max(time) - min(time),
            time.med = median(time))
```

```{r}
#'get a list with one list per high tide: each row a foraging segment, two columns for coordinates, and one matrix per id
data.list = data.segpaths %>% 
  mutate(ht = stri_pad(substr(as.character(id.ht), 5,7), side = "right", width = 3, pad = "0"),
         id = substr(as.character(id.ht), 1, 3)) %>% 
  dlply("ht") %>% 
  map(function(x){
    x %>% 
      dlply("id")
  })
```

```{r create_holding_list}
#'write this description later
#'in each segment of each focal bird, how many segments of the other bird(s) was(ere) within 250m and within half the segment duration?

#'test run, get only three dfs
#'full run, get all dfs

library(sp)

n.birds = 41

#'make a list of lists, each element of the list is a single tide
proximity.list = vector("list", length(data.list)) %>% 
  map(function(x) {vector("list", n.birds) %>% 
      map(vector("list", n.birds-1))})
```

```{r make_prox_data}
#'write a description here

for(ht in 1:length(data.list)){
  a = data.list[[ht]]

#'this is only one high tide
for(i in 1:length(a)){
  b = a[!names(a) %in% names(a)[i]]
  for(j in 1:length(b)){
    f1 = as.matrix(a[[i]][,c("x.med","y.med")])
    f2 = as.matrix(b[[j]][,c("x.med","y.med")])
    
    dist.matrix = spDists(x = f1, y = f2)
    time.matrix = outer(a[[i]]$time.med, b[[j]]$time.med, FUN = "-")
    
    temp.prox = apply(time.matrix, 2, function(x) abs(x) <= a[[i]]$seg.dur/2)
    
    dist.matrix[temp.prox == F | dist.matrix <= 200] = NA
    seg.prox.count = apply(dist.matrix, 1, function(x) sum(!is.na(x)))
    
    proximity.list[[ht]][[i]][[j]] = seg.prox.count
    
  }
  #'assign names to level 3
  names(proximity.list[[ht]][[i]]) = names(b)
  #'collapse the third level of lists into a df
  proximity.list[[ht]][[i]] = proximity.list[[ht]][[i]] %>% bind_rows() %>% 
    mutate(id = names(a)[i],
           seg = 1:length(id),
           ht = names(data.list)[ht]) %>% 
    melt(id.vars = c("id","seg","ht"))
  #'assign names to level 2
  names(proximity.list[[ht]]) = names(a)
  }
}

#'set ht name
names(proximity.list) = names(data.list)
```

```{r}
#'now bind within ht to get a unified df
proximity.list = proximity.list %>% 
  map(bind_rows) %>% 
  bind_rows()
```

```{r}
#'split by ht, and cast by the formula id+seg ~ variable
prox.mat = proximity.list %>% 
  select(-seg) %>% 
  dcast(id+ht~variable, drop = F, fun.aggregate = sum, fill = -1) %>% 
  dlply("ht") %>% 
  map(function(x) x %>% select(-ht))
 
```

```{r}

```

