---
editor_options: 
  chunk_output_type: console
---

```{r load_libs}
source("libs.R")
library(readr);library(viridis)
source("libs.spatial.r")
library("plyr")
```

```{r load_data}
#'loadpskf data
#load("knots_data/pskf_data.rdata")
```

```{r make_lines}
#'use same template as k2-data
k2.lines = knots2 %>% mutate(id.seg = paste(id,day,sep = "_")) %>% dlply("id.seg") %>% map(function(x)x %>% arrange(TIME)) %>% 
  #map(function(x) x %>% filter(Std<100)) %>% 
  map(function(x) Line(cbind(x$X, x$Y)))

k2.lines = k2.lines %>% 
  map(function(x) Lines(x, ID = "a"))

for(i in 1:length(k2.lines)){
  k2.lines[[i]]@ID = names(k2.lines)[i]
}
```

```{r make_spatial_lines}
names = names(k2.lines)

#'use the UTM 31N CRS
k2.lines = SpatialLines(k2.lines, proj4string = CRS("+proj=utm +zone=31 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
+towgs84=0,0,0"))

library(stringi)

data = data_frame(index = 1:length(k2.lines),names2 = names) %>% left_join(pskf_data_ids, by = c("names2" = "id.seg"))

rownames(data) = names

k2.lines = SpatialLinesDataFrame(k2.lines, data = data)

#'export
library(rgdal)
writeOGR(k2.lines, dsn = "knots_data/knots_spatials/", layer = "k2_lines_raw", driver = "ESRI Shapefile", overwrite_layer = T)
```

