---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
source("libs.R");load("knots_data/distance_matrix.rdata")
library(readxl); library(viridis)
```

```{r load_behav_data}
#'load the beahvioural scores from the excel file sheet 4
library(readxl)
k2.behav = read_excel("knots_data/eva-tagnr toa sept15.xlsx", sheet = 4) %>% mutate(id = as.character(tagnr), exp = as.numeric(exp))
```

```{r get_distances}
#'get the NND, the N5D at each time step where there is data for at least one bird, ie, the whole row is not NA.
k2.dm = e %>% map(function(x) x[apply(x, 1, function(y) sum(!is.na(y))>0),] %>%  mutate(time = k2.time$time_calc[apply(x, 1, function(y) sum(!is.na(y))>0)]) %>% melt(id.vars = "time") %>% group_by(time) %>% arrange(value) %>% summarise(nn.id = first(variable), nnd = min(sort(value)), n5d = mean(head(sort(value)))))
```

```{r merge_distance_data}
#'assign id
for (i in 1:length(k2.dm)) {
  k2.dm[[i]]$id = names(k2.dm)[i]  
}

#'bind rows
k2.dm = k2.dm %>% bind_rows()
```

```{r join_behav_nnd_data}
#'join the dataframes based on the id
k2.data = left_join(k2.dm, k2.behav %>% select(exp, id), by = "id") %>% left_join(k2.behav %>% rename(nn.exp = exp, nn.id = id) %>% select(nn.exp, nn.id), by = "nn.id")
```

```{r load_tide_times}
#'load the tide data and join to the k2.time df, find the time since each tide
load("k2.tides.rdata")

k2.time = full_join(k2.time %>% mutate(time = as.POSIXct(time_calc, origin = "1970-01-01", tz = "CEST")), tide, by = "time") %>% arrange(time)

k2.time = k2.time %>% mutate(tide = ifelse(is.na(tide), "other", tide), high = cumsum(tide == "H")) %>% group_by(high) %>% mutate(h_since_ht = as.numeric(time - time[1])/3600)
```

```{r join_to_k2.data}
#'join the tidal time df by the numeric time column to the main data
k2.data = k2.data %>% left_join(k2.time, by = c("time" = "time_calc"))
```

```{r plot_delta.exp_time}
#'plot both by time and tidal time

png(filename = "knots_figs/delta.explore.score_nnd.png", width = 1600, height = 1600,res = 400)

k2.data %>% mutate(nnd.round = round_any(nnd, 50)) %>% melt(id.vars = c("nnd.round"),measure.vars = c("exp","nn.exp")) %>% group_by(nnd.round, variable) %>% summarise(mean = mean(value)) %>% dcast(nnd.round ~ variable, mean) %>% 
  ggplot()+
  geom_point(aes(y = nnd.round, x = exp - nn.exp, fill = exp), size = 2, shape = 21, col = 1, stroke = 0.1)+
  labs(list(x = "Δ explore score (focal - NN)", y = "NND (m)", fill = "explore_score_focal"))+
  coord_flip()+
  scale_fill_viridis_c()+
  theme_pub()+
  theme(legend.position = "top")

dev.off()

```

```{r unique_neighbours}
#'count the number of unique neighbours
png(filename = "knots_figs/neighbours_time.png", width = 1600, height = 1600,res = 400)

k2.data %>% filter(time > as.numeric(k2.time$time[300])) %>% group_by(expround = round_any(exp,0.2), timeround = round_any(time, 3600)) %>% group_by(id) %>% mutate(nbrs = cumsum(!duplicated(nn.id))) %>%  melt(id.vars = c("expround","timeround"), measure.vars = c("nbrs")) %>% group_by(timeround, expround) %>% summarise(mean = mean(value),sd = sd(value)) %>% 
  bind_rows() %>% 
  ggplot()+
  geom_point(aes(x = timeround - k2.time$time_calc[300], y = mean, fill = expround), shape = 21, col = 1, size = 2, stroke= 0.1)+
  scale_fill_viridis_c()+
  theme_pub()+
  #coord_cartesian(ylim = c(20, 41))+
  theme(legend.position = "top")+
  labs(list(x = "time (s after 3:39 pm 15/09/17)", y = "# unique nearest neighbours", fill = "explore_score"))

dev.off()
```

```{r exp_and_nnexp}
#'plot the exploration score of the nearest neighbour over time and over tidal time
png(filename = "knots_figs/nnexp_tidaltime.png", width = 1600, height = 1600,res = 400)

k2.data %>% filter(time > as.numeric(k2.time$time[300])) %>% group_by(expround = round_any(exp,0.2), tidetimeround = round_any(h_since_ht, 0.5)) %>% group_by(id) %>% mutate(nbrs = cumsum(!duplicated(nn.id))) %>%  melt(id.vars = c("expround","tidetimeround"), measure.vars = c("nn.exp")) %>% group_by(tidetimeround, expround) %>% summarise(mean = mean(value),sd = sd(value)) %>%
  
  ggplot()+
  geom_point(aes(x = tidetimeround, y = mean, fill = expround), shape = 21, col = 1, size = 2, stroke= 0.1)+
  geom_vline(aes(xintercept = k2.data %>% filter(tide == "L") %>% summarise(h = mean(h_since_ht)) %>% .$h), col = "red")+
  scale_fill_viridis_c()+
  theme_pub()+
  #coord_cartesian(ylim = c(20, 41))+
  theme(legend.position = "top")+
  labs(list(x = "time since high tide (hrs)", y = "exp_score NN", fill = "explore_score_focal"))

dev.off()
```


```{r plot_ndvstime}
#'separate by id

png(filename = "knots_figs/nearest_neighbours_tidaltime.png", width = 3200, height = 1600,res = 400)

k2.data %>% mutate(tidal_time = round_any(h_since_ht, 0.5), exp_round = as.factor(round_any(exp, 0.2))) %>% melt(id.vars = c("tidal_time", "exp_round"),measure.vars = c("nnd","n5d")) %>% group_by(tidal_time, exp_round, variable) %>% summarise(mean = mean(value)) %>% #dcast(time_round + exp_round ~ variable, mean) %>%
  ggplot()+
  geom_point(aes(x = tidal_time, y = mean, fill = exp_round), size = 3, shape = 21, position = position_dodge(width = 0.2), col = "transparent")+
  geom_vline(aes(xintercept = k2.data %>% filter(tide == "L") %>% summarise(h = mean(h_since_ht)) %>% .$h), col = "red")+
  ylim(NA, 3e3)+
  facet_wrap(~variable, scales = "free")+
  scale_fill_brewer(palette = "PiYG")+
  labs(list(x = "hrs since HT", y = "nearest neigbours (m)", fill = "explore_score"))+
  theme_pub()+theme(legend.position = "top", legend.key = element_blank())
dev.off()
```

