---
editor_options: 
  chunk_output_type: console
---

```{r load_libs}
source("libs.R");source("ggplot.pub.r")
library(readr);library(viridis)
```

```{r load_cleaned_subset_data}
#'load knots01_data
load("knots_data/knots01_data.rdata")
load("knots_data/knots02_data.rdata")
load("knots_data/sanderling_data.rdata")
```

```{r temporal_range}
#'gather all birds
birds.all = append(k1.data, c(k2.data, sanderling.data))
#'remove the main data and gc
rm(k1.data, k2.data, sanderling.data);gc()

#'assign tag id
for (i in 1:length(birds.all)){
  birds.all[[i]]$id = names(birds.all)[i]
}

#'bind rows
birds.all = birds.all %>% bind_rows()

#'assign species and batch id
birds.all = birds.all %>% mutate(batch = ifelse(as.numeric(id) < 151, "sanderling", ifelse(as.numeric(id) < 255, "knots01", "knots02")), sp = ifelse(batch != "sanderling", "knot", "sanderling"))

#'save as rdata
save(birds.all, file = "birds.all.rdata")
```

```{r summarise_data}
#'summary for id and time
#summary(k1)
count(birds.all, id)

#'get the tracking day
birds.all = birds.all %>% mutate(day = round_any(as.numeric(julian(ts, origin = min(birds.all$ts))), 0.1))

```

```{r plot_fix_density, eval=FALSE, include=FALSE}
#'plot a density curve
ggplot(k1)+
  stat_density(aes(x = day, group = id, col = id), geom = "line")+
  theme_pub()

#'plot the number of positions per day per bird
birds.all %>% group_by(id, day, batch) %>% summarise(n = length(ts)) %>% 
ggplot()+
  geom_tile(aes(x = id, y = day, fill = n))+
  scale_fill_gradientn(colours  = (plasma(20)))+
  facet_wrap(~batch, scales = "free_y")+
  coord_flip()+
  theme_pub()+
  theme(legend.position = "top", axis.line.y = element_blank(), legend.text = element_text(angle= 10), 
        #legend.background = element_rect(fill = 1), plot.background = element_rect(fill=1), axis.text = element_text(colour = "white"), legend.title = element_text(colour = "white"), strip.text = element_text(colour = "white")
        )+
  labs(list(fill = "fixes", y = "days since 07/27/2017"))
```

```{r reduce_data}
#'reduce data to 1 minute intervals


```

