```{r}
#'load data
load("knots2_3day_data.rdata")
source("libs.R")
```

```{r}
#'get the explore score for each bird
library(readxl)
k2.behav = read_excel("knots_data/eva-tagnr toa sept15.xlsx", sheet = 4) %>% mutate(id = as.character(tagnr), exp = as.numeric(exp))
```

```{r}
#'get tidal data
load("k2.tides.rdata")

#'join tides and pos data
k2.2 = k2.2 %>% dlply("id") %>% map(function(x) {x %>% 
    full_join(tide %>% 
                mutate(time_num = as.numeric(time)), by = c("time_round" = "time_num")) %>% 
    arrange(time_round) %>% 
    mutate(tide = ifelse(is.na(tide), "other", tide), high = cumsum(tide == "H"), low = cumsum(tide == "L")) %>% 
    group_by(high) %>% 
    mutate(h_since_ht = as.numeric(time_round - time_round[1])/3600) %>% 
    ungroup() %>% 
    group_by(low) %>% 
    mutate(h_since_lt = as.numeric(time_round - time_round[1])/3600) %>%
    ungroup() %>% 
    arrange(time_round) %>% 
    mutate(seg = cumsum(tide != "other"))})
```

```{r}
#'distance of LT pos from HT pos
k2dists = k2.2 %>% 
  bind_rows() %>% 
  dlply(c("id","seg"))

#'remove no data dfs
k2dists = k2dists[!is.na(lapply(k2dists, function(x) unique(x$id)))]

#'run on that data
k2dists = k2dists %>% 
  summarise(segdist = dist(rbind(c(first(X), first(Y)),
                                 c(last(X), last(Y)))),
            id = first(id),
            t)
```

