---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#'load libs
source("libs.R")
library(readr)
```

```{r}
#'load data
waterlevel.harlingen = read_delim("knots_data/waterdata-HAR_WTER_VLIE-201706010000_201711012359.txt", delim = ";", skip = 3) %>% select(date = datum, time = tijd, level = waarde, site = locatie) %>% mutate(date = as.character(date))

waterlevel.terschelling = read_delim("knots_data/08-14-2017 - 09-09-2017 - gemeten waterhoogte west terschelling.csv", delim = ";") %>% select(date = Datum, time = Tijd, level = Meting, site = Locatie)

waterlevels = bind_rows(waterlevel.harlingen, waterlevel.terschelling) %>%
  mutate(date_time = as.POSIXct(paste(date,time,sep = " "), format = "%Y-%m-%d %H:%M:%S")) %>% 
  arrange(date_time) %>% 
  filter(date_time %between% c("2017-08-23","2017-09-23")) %>% 
  filter(duplicated(date_time) == F)
```

```{r}
#'load function for high and low tide
source("knots_data_functions/high_low_tide.R")
```

```{r}
#'pass data to function
tide = HL(level = waterlevels$level, time = waterlevels$date_time)
```

```{r}
#'save data
save(tide, file = "k1.tides.rdata")
```


